
pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
                //Jalar el proyecto de git
                git url: 'https://github.com/DarlingOlvera/Tareas.git',branch: 'dev'
                
            }
        }
        stage('Install dependencies and do tests'){
            steps{
                dir(/SiceiExpress){
                    sh 'npm install'
                    sh 'npm run test'
                }
            }
        }

    }
}